<a href="https://colab.research.google.com/github/yadavrahyl2k15/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np

In [34]:
a=np.array
print(a)

<built-in function array>


In [35]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [36]:
type(a)

numpy.ndarray

In [37]:
b=np.array([1,2,3,4],complex)
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [38]:
c=np.array([1,2,3,4],float)
c

array([1., 2., 3., 4.])

In [39]:
type(b)

numpy.ndarray

In [40]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print("each item contains",a.itemsize,"bytes")

each item contains 8 bytes


In [42]:
print("each item contains",b.itemsize,"bytes")

each item contains 16 bytes


In [43]:
print("each item contains",d.itemsize,"bytes")

each item contains 8 bytes


In [44]:
print("each items of type : ",a.dtype)

each items of type :  int64


In [45]:
print("each items of type : ",b.dtype)

each items of type :  complex128


In [46]:
print("each items of type : ",d.dtype)

each items of type :  int64


SHAPE AND SIZE OF ARRAY

In [47]:
print("shape of array :",a.shape)
print("size of array :",a.size)

shape of array : (5,)
size of array : 5


In [48]:
print("shape of array :",b.shape)
print("size of array :",b.size)

shape of array : (4,)
size of array : 4


In [49]:
print("shape of array :",d.shape)
print("size of array :",d.size)

shape of array : (2, 3)
size of array : 6


RESHAPING ARRAY

In [50]:
a=np.array([[1,2],[56,87],[12,566],[45,76]])
print("array shape before reshaping: ",a.shape)
b=a.reshape(8,1)
print("array shape after reshaping :",b.shape)
print(b)

array shape before reshaping:  (4, 2)
array shape after reshaping : (8, 1)
[[  1]
 [  2]
 [ 56]
 [ 87]
 [ 12]
 [566]
 [ 45]
 [ 76]]


SLICING OF ARRAY

In [51]:
a=np.array([[32,54],[12,45],[45,67]])
print(a[1,1])
print(a[0,1])
print(a[2,0])

45
54
45


LINSPACE

In [52]:
a=np.linspace(2,10,15)
a

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

operations

In [53]:
a=np.array([12,23,43,53,56,12,278,7,90,23])
print("maximum of array:",a.max())
print("minimum of array:",a.min())
print("sum of array :",a.sum())
print("square root of array :",np.sqrt(a))
print("standard deviation of array:",np.std(a))

maximum of array: 278
minimum of array: 7
sum of array : 597
square root of array : [ 3.46410162  4.79583152  6.55743852  7.28010989  7.48331477  3.46410162
 16.673332    2.64575131  9.48683298  4.79583152]
standard deviation of array: 76.76724561946978


CONCATENATION

In [54]:
a=np.array([[1,2,3],[43,45,21]])
b=np.array([[32,21,210],[90,21,0]])

print("array vertically concatenate : \n",np.vstack((a,b)))
print("array horizontal concatenate : \n",np.hstack((a,b)))

array vertically concatenate : 
 [[  1   2   3]
 [ 43  45  21]
 [ 32  21 210]
 [ 90  21   0]]
array horizontal concatenate : 
 [[  1   2   3  32  21 210]
 [ 43  45  21  90  21   0]]


ARRAY CREATON

In [55]:
array=np.empty((3,3),dtype=float)
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
array=np.empty((2,2))
array

array([[1., 2.],
       [3., 4.]])

In [57]:
array=np.zeros((4,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
array=np.ones((3,3),dtype=float)
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

NUMPY ARRAY FROM EXISTING DATA

In [59]:
tupl=(1,2,3,4,5,6)
a=np.asarray(tupl)
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [60]:
list1=[[1,2,3,4,5,6],[5,6,45]]
a=np.asarray(list1)
print(a)
print(type(a))

[list([1, 2, 3, 4, 5, 6]) list([5, 6, 45])]
<class 'numpy.ndarray'>


/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [61]:
string=b"hello world"
print(type(string))
a=np.frombuffer(string,dtype="S1")
print(a)

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [62]:
list1=[1,2,3,4,5]
it=iter(list1)
a=np.fromiter(it,dtype=float)
print(a)
print(type(a))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


NUMPY FROM ITERATION

In [63]:
import numpy as np


In [64]:
a=np.array([[1,2,3],[34,56,23],[98,23,12]])
for x in np.nditer(a):
  print(a ,end='')

[[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]][[ 1  2  3]
 [34 56 23]
 [98 23 12]]

In [65]:
a_transpose=a.T
print(a_transpose)

[[ 1 34 98]
 [ 2 56 23]
 [ 3 23 12]]


In [66]:
for x in np.nditer(a_transpose):
  print(x,end=" ")

1 2 3 34 56 23 98 23 12 

NUMPY BITWISE OPERATIONS

In [67]:
import numpy as np
a=10
b=12
print(bin(a))
print(bin(b))

0b1010
0b1100


In [68]:
print("Bitwise AND :",np.bitwise_and(a,b))
print(bin(np.bitwise_and(a,b)))

Bitwise AND : 8
0b1000


In [69]:
print("Bitwise OR : ",np.bitwise_or(a,b))
print(bin(np.bitwise_or(a,b)))

Bitwise OR :  14
0b1110


In [70]:
array=np.array([20],dtype=np.uint8)
print("Binary Representation :",np.binary_repr(20))
print(np.invert(array))


Binary Representation : 10100
[235]


In [71]:
print("Binary Representation :",np.binary_repr(235))

Binary Representation : 11101011


In [72]:
print("left shift of 20 by 3 bits:",np.left_shift(20,3))

left shift of 20 by 3 bits: 160


In [73]:
print("right shift of 20 by 3 bits:",np.right_shift(20,3))

right shift of 20 by 3 bits: 2


In [74]:
np.char.join(":","welcome to future")

array('w:e:l:c:o:m:e: :t:o: :f:u:t:u:r:e', dtype='<U33')

In [75]:
np.char.multiply("hello",3)

array('hellohellohello', dtype='<U15')

In [76]:
np.char.center("python",20,"#")

array('#######python#######', dtype='<U20')

In [77]:
np.char.capitalize("welcome to future")

array('Welcome to future', dtype='<U17')

In [78]:
np.char.title("welcome to future")

array('Welcome To Future', dtype='<U17')

In [79]:
st="happy journey"
np.char.replace(st,"happy","nice")

array('nice journey', dtype='<U12')

MATHMATICAL FUNCTION

In [80]:
array=np.array([0,20,45,180])
print("Sin value:",np.sin(array*np.pi/180))
print("Cos value:",np.cos(array*np.pi/180))
print("Tan value:",np.tan(array*np.pi/180))

Sin value: [0.00000000e+00 3.42020143e-01 7.07106781e-01 1.22464680e-16]
Cos value: [ 1.          0.93969262  0.70710678 -1.        ]
Tan value: [ 0.00000000e+00  3.63970234e-01  1.00000000e+00 -1.22464680e-16]


In [81]:
array=np.array([21,43,67,87,98])
np.around(array,-1)

array([ 20,  40,  70,  90, 100])

In [82]:
np.floor(12.8932)

12.0

In [83]:
np.ceil(23.12)

24.0

In [84]:
a=np.array([[12,32,2],[43,123,98],[54,543,76]])
print("minimum element among the row:",np.amin(a,0))
print("minimum element among the column:",np.amin(a,1))

minimum element among the row: [12 32  2]
minimum element among the column: [ 2 43 54]


In [85]:
print("maximum element among the row",np.amax(a,0))
print("maximum element among the column",np.amax(a,1))

maximum element among the row [ 54 543  98]
maximum element among the column [ 32 123 543]


In [87]:
print("pecentile 10 along row:",np.percentile(a,10,0))

pecentile 10 along row: [18.2 50.2 16.8]


In [88]:
print("percentile 30 along column:",np.percentile(a,30,1))

percentile 30 along column: [ 8.  76.  67.2]


In [90]:
print("mean along axis 0:",np.mean(a,0))

mean along axis 0: [ 36.33333333 232.66666667  58.66666667]


SORTING

In [93]:
a=np.array([[10,2,3],[34,21,56],[13,67,43]])
print("sorting array:",np.sort(a))
print("sorting array along axis 0:",np.sort(a,0))
print("sorting array along axis 1:",np.sort(a,1))

sorting array: [[ 2  3 10]
 [21 34 56]
 [13 43 67]]
sorting array along axis 0: [[10  2  3]
 [13 21 43]
 [34 67 56]]
sorting array along axis 1: [[ 2  3 10]
 [21 34 56]
 [13 43 67]]


SEARCHING

In [96]:
a=np.array([21,32,45,143,564,23,321,90,102])
print(np.where(a>100))

(array([3, 4, 6, 8]),)


ID,COPY,VIEW

In [99]:
a=np.array([[1,2,3],[12,23,123],[453,45,67]])
print("id of a is:",id(a))

b=a

print("id of b is:",id(b))

b.shape=(9,1)

print(a.shape)

id of a is: 139661874426384
id of b is: 139661874426384
(9, 1)


In [100]:
a=np.array([[1,2,3],[12,23,123],[453,45,67]])
print("id of a is:",id(a))

b=a.view()

print("id of b is:",id(b))

b.shape=(9,1)

print(a.shape)

id of a is: 139661874480752
id of b is: 139661874481472
(3, 3)


In [102]:
a=np.array([[1,2,3],[12,23,123],[453,45,67]])
print("id of a is:",id(a))

b=a.copy()
print(b)
print("id of b is:",id(b))

b.shape=(9,1)

print(a.shape)

id of a is: 139661874939984
[[  1   2   3]
 [ 12  23 123]
 [453  45  67]]
id of b is: 139661875202848
(3, 3)


SAVE

In [103]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.save("sample",a)


In [105]:
b=np.load("sample.npy")
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])